- src: https://github.com/iMartzen/ansible-role-python-centos-bootstrap
  version: setupforcentos

- src: https://github.com/iMartzen/ansible-role-centos-system-upgrade
  version: setupforcentos

- src: https://github.com/iMartzen/ansible-role-centos-docker-compose-setup
  version: setupforcentos

- src: https://github.com/AdnanHodzic/ansible-role-containerized-wordpress
